<?php
Route::get('/loaisanpham/{id?}','HomeController@loaisp')->name('home.loaisp');
Route::get('','HomeController@index')->name('home.index');
Route::get('/chitietsp/{id?}','HomeController@chitietsp')->name('home.chitietsp');
Route::get('/lienhe','HomeController@lienhe')->name('home.lienhe');
Route::get('/gioithieu','HomeController@gioithieu')->name('home.gioithieu');
Route::get('add-to-cart/{id?}','HomeController@addtocart')->name('home.addtocart');
Route::get('delete-one-cart/{rowId?}','HomeController@delete_one_cart')->name('home.delete_one_cart');
Route::get('deletecart','HomeController@deletecart')->name('home.deletecart');
Route::get('dathang','HomeController@dathang')->name('home.dathang');
Route::post('xacnhandathang','HomeController@xacnhandathang')->name('home.xacnhandathang');
Route::get('login','HomeController@login')->name('home.login');
Route::post('dangnhap','HomeController@dangnhap')->name('home.dangnhap');
Route::get('dangxuat','HomeController@dangxuat')->name('home.dangxuat');
Route::get('sigup','HomeController@sigup')->name('home.sigup');
Route::post('sigin','HomeController@postsigup')->name('home.postsigup');
Route::get('search','HomeController@search')->name('home.search');

//backend
Route::get('admin/login','Admin\LoginController@login')->name('admin.login');
Route::get('admin/logout','Admin\LoginController@logout')->name('admin.logout');
